"""initial migration

Revision ID: ff93b60e65bf
Revises: 
Create Date: 2026-04-30 13:26:50.691847-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff93b60e65bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_especialidades_id'), 'cat_especialidades', ['id'], unique=False)
    op.create_table('cat_estados_cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_estados_cita_id'), 'cat_estados_cita', ['id'], unique=False)
    op.create_table('cat_medios_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_medios_contacto_id'), 'cat_medios_contacto', ['id'], unique=False)
    op.create_table('cat_nacionalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_nacionalidades_id'), 'cat_nacionalidades', ['id'], unique=False)
    op.create_table('cat_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_roles_id'), 'cat_roles', ['id'], unique=False)
    op.create_table('cat_servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio_base', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_servicios_id'), 'cat_servicios', ['id'], unique=False)
    op.create_table('cat_sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_sucursales_id'), 'cat_sucursales', ['id'], unique=False)
    op.create_table('cat_tipos_antecedentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_tipos_antecedentes_id'), 'cat_tipos_antecedentes', ['id'], unique=False)
    op.create_table('cat_tipos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cat_tipos_paciente_id'), 'cat_tipos_paciente', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('nacionalidad_id', sa.Integer(), nullable=True),
    sa.Column('telefono_principal', sa.String(length=20), nullable=True),
    sa.Column('telefono_secundario', sa.String(length=20), nullable=True),
    sa.Column('email_secundario', sa.String(length=100), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimo_acceso', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['nacionalidad_id'], ['cat_nacionalidades.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['cat_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_curp'), 'usuarios', ['curp'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('numero_empleado', sa.String(length=20), nullable=True),
    sa.Column('cedula_profesional', sa.String(length=20), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('salario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['cat_sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_profesional'),
    sa.UniqueConstraint('numero_empleado'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_empleados_activo'), 'empleados', ['activo'], unique=False)
    op.create_index(op.f('ix_empleados_id'), 'empleados', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_paciente_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('telefono_emergencia', sa.String(length=20), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=100), nullable=True),
    sa.Column('tutor_nombre', sa.String(length=200), nullable=True),
    sa.Column('tutor_telefono', sa.String(length=20), nullable=True),
    sa.Column('tutor_relacion', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['cat_sucursales.id'], ),
    sa.ForeignKeyConstraint(['tipo_paciente_id'], ['cat_tipos_paciente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_pacientes_activo'), 'pacientes', ['activo'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('bloqueos_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_bloqueo', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['cat_sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueos_agenda_fecha_fin'), 'bloqueos_agenda', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_bloqueos_agenda_fecha_inicio'), 'bloqueos_agenda', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_bloqueos_agenda_id'), 'bloqueos_agenda', ['id'], unique=False)
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('estado_cita_id', sa.Integer(), nullable=False),
    sa.Column('medio_contacto_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('notas_cancelacion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['estado_cita_id'], ['cat_estados_cita.id'], ),
    sa.ForeignKeyConstraint(['medio_contacto_id'], ['cat_medios_contacto.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['cat_servicios.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['cat_sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_empleado_id'), 'citas', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_citas_fecha'), 'citas', ['fecha'], unique=False)
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_index(op.f('ix_citas_paciente_id'), 'citas', ['paciente_id'], unique=False)
    op.create_table('empleado_especialidades',
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['especialidad_id'], ['cat_especialidades.id'], ),
    sa.PrimaryKeyConstraint('empleado_id', 'especialidad_id')
    )
    op.create_table('historial_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_antecedente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_diagnostico', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_antecedente_id'], ['cat_tipos_antecedentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_clinico_id'), 'historial_clinico', ['id'], unique=False)
    op.create_index(op.f('ix_historial_clinico_paciente_id'), 'historial_clinico', ['paciente_id'], unique=False)
    op.create_table('consentimientos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('texto_consentimiento', sa.Text(), nullable=False),
    sa.Column('firma_paciente', sa.Text(), nullable=True),
    sa.Column('ip_registro', sa.String(length=50), nullable=True),
    sa.Column('fecha_consentimiento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['cat_servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimientos_paciente_id'), 'consentimientos_paciente', ['id'], unique=False)
    op.create_index(op.f('ix_consentimientos_paciente_paciente_id'), 'consentimientos_paciente', ['paciente_id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('reconocimiento_hallazgos', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento_indicaciones', sa.Text(), nullable=True),
    sa.Column('peso', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('talla', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('temperatura', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('pulso', sa.Integer(), nullable=True),
    sa.Column('glucosa', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notas_adicionales', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    op.create_index(op.f('ix_consultas_empleado_id'), 'consultas', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_index(op.f('ix_consultas_paciente_id'), 'consultas', ['paciente_id'], unique=False)
    op.create_table('consultas_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('tipo_foto', sa.String(length=20), nullable=False),
    sa.Column('url_foto', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['cat_servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_fotos_consulta_id'), 'consultas_fotos', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_consultas_fotos_id'), 'consultas_fotos', ['id'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('talla', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('temperatura', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('pulso', sa.Integer(), nullable=True),
    sa.Column('glucosa', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('indicaciones_generales', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consulta_id')
    )
    op.create_index(op.f('ix_recetas_empleado_id'), 'recetas', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_recetas_folio'), 'recetas', ['folio'], unique=True)
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    op.create_index(op.f('ix_recetas_paciente_id'), 'recetas', ['paciente_id'], unique=False)
    op.create_table('receta_medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('medicamento', sa.String(length=200), nullable=False),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=False),
    sa.Column('duracion', sa.String(length=100), nullable=True),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_medicamentos_id'), 'receta_medicamentos', ['id'], unique=False)
    op.create_index(op.f('ix_receta_medicamentos_receta_id'), 'receta_medicamentos', ['receta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receta_medicamentos_receta_id'), table_name='receta_medicamentos')
    op.drop_index(op.f('ix_receta_medicamentos_id'), table_name='receta_medicamentos')
    op.drop_table('receta_medicamentos')
    op.drop_index(op.f('ix_recetas_paciente_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_folio'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_empleado_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_consultas_fotos_id'), table_name='consultas_fotos')
    op.drop_index(op.f('ix_consultas_fotos_consulta_id'), table_name='consultas_fotos')
    op.drop_table('consultas_fotos')
    op.drop_index(op.f('ix_consultas_paciente_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_empleado_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_consentimientos_paciente_paciente_id'), table_name='consentimientos_paciente')
    op.drop_index(op.f('ix_consentimientos_paciente_id'), table_name='consentimientos_paciente')
    op.drop_table('consentimientos_paciente')
    op.drop_index(op.f('ix_historial_clinico_paciente_id'), table_name='historial_clinico')
    op.drop_index(op.f('ix_historial_clinico_id'), table_name='historial_clinico')
    op.drop_table('historial_clinico')
    op.drop_table('empleado_especialidades')
    op.drop_index(op.f('ix_citas_paciente_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_fecha'), table_name='citas')
    op.drop_index(op.f('ix_citas_empleado_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_bloqueos_agenda_id'), table_name='bloqueos_agenda')
    op.drop_index(op.f('ix_bloqueos_agenda_fecha_inicio'), table_name='bloqueos_agenda')
    op.drop_index(op.f('ix_bloqueos_agenda_fecha_fin'), table_name='bloqueos_agenda')
    op.drop_table('bloqueos_agenda')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_activo'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_empleados_id'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_activo'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_curp'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cat_tipos_paciente_id'), table_name='cat_tipos_paciente')
    op.drop_table('cat_tipos_paciente')
    op.drop_index(op.f('ix_cat_tipos_antecedentes_id'), table_name='cat_tipos_antecedentes')
    op.drop_table('cat_tipos_antecedentes')
    op.drop_index(op.f('ix_cat_sucursales_id'), table_name='cat_sucursales')
    op.drop_table('cat_sucursales')
    op.drop_index(op.f('ix_cat_servicios_id'), table_name='cat_servicios')
    op.drop_table('cat_servicios')
    op.drop_index(op.f('ix_cat_roles_id'), table_name='cat_roles')
    op.drop_table('cat_roles')
    op.drop_index(op.f('ix_cat_nacionalidades_id'), table_name='cat_nacionalidades')
    op.drop_table('cat_nacionalidades')
    op.drop_index(op.f('ix_cat_medios_contacto_id'), table_name='cat_medios_contacto')
    op.drop_table('cat_medios_contacto')
    op.drop_index(op.f('ix_cat_estados_cita_id'), table_name='cat_estados_cita')
    op.drop_table('cat_estados_cita')
    op.drop_index(op.f('ix_cat_especialidades_id'), table_name='cat_especialidades')
    op.drop_table('cat_especialidades')
    # ### end Alembic commands ###
